import type { LocaleKeyMap } from "../types/index.js";

/**
 * Built-in mapping from common sheet column header spellings to BCP-47 codes.
 *
 * The sheet's own `_keymap` tab and the caller's `localeKeyMap` option are
 * merged on top of this at runtime, so any entry here can be overridden.
 */
export const DEFAULT_LOCALE_KEY_MAP: LocaleKeyMap = {
  // Short codes
  EN: "en",
  ENG: "en",
  CHT: "zh-TW",
  CHS: "zh-CN",
  SCH: "zh-CN",
  TCH: "zh-TW",
  CZE: "cs",
  DAN: "da",
  DUT: "nl",
  FIN: "fi",
  FRE: "fr",
  GER: "de",
  GRK: "el",
  HUN: "hu",
  ITA: "it",
  JPN: "ja",
  KOR: "ko",
  NOR: "no",
  POL: "pl",
  POR: "pt",
  ROM: "ro",
  RUS: "ru",
  SPA: "es",
  SWE: "sv",
  THA: "th",
  TUR: "tr",

  // Long codes with parenthetical hints
  "TCH (Tchinese)": "zh-TW",
  "SCH (Schinese)": "zh-CN",
  "CZE (Czech)": "cs",
  "DAN (Danish)": "da",
  "DUT (Dutch)": "nl",
  "FIN (Finnish)": "fi",
  "FRE (French)": "fr",
  "GER (German)": "de",
  "GRK (Greek)": "el",
  "HUN (Hungarian)": "hu",
  "ITA (Italian)": "it",
  "JPN (Japanese)": "ja",
  "KOR (Korean)": "ko",
  "NOR (Norwegian)": "no",
  "POL (Polish)": "pl",
  "POR (Portuguese-Brazil)": "pt",
  "ROM (Romanian)": "ro",
  "RUS (Russian)": "ru",
  "SPA (Spanish-Latin)": "es",
  "SWE (Swedish)": "sv",
  "THA (Thai)": "th",
  "TUR (Turkish)": "tr",

  // Full English names
  English: "en",
  Czech: "cs",
  Danish: "da",
  Dutch: "nl",
  Finnish: "fi",
  French: "fr",
  German: "de",
  Greek: "el",
  Hungarian: "hu",
  Italian: "it",
  Japanese: "ja",
  Korean: "ko",
  Norwegian: "no",
  Polish: "pl",
  Portuguese: "pt",
  Romanian: "ro",
  Russian: "ru",
  "Spanish (Spain)": "es",
  Swedish: "sv",
  Thai: "th",
  Turkish: "tr",

  // Native names
  "繁體中文": "zh-TW",
  "简体中文": "zh-CN",
  Dansk: "da",
  Nederlands: "nl",
  Suomi: "fi",
  Français: "fr",
  Deutsch: "de",
  "Ελληνικά": "el",
  Magyar: "hu",
  Italiano: "it",
  "日本語": "ja",
  "한글": "ko",
  Norsk: "no",
  Polski: "pl",
  "Português": "pt",
  "Română": "ro",
  "Русский": "ru",
  "Español": "es",
  Svenska: "sv",
  "ไทย": "th",
  "Turk dili": "tr",
};
